### ISSUE TITLE
"Dll not specified for the current platform" error when running on FreeBSD

### ISSUE THREAD

**Issue by AAM1075** [HexaEngine/Hexa.NET.Raylib#1]
When compiling and running my project that uses this library, I receive the following error:
![image](https://github.com/user-attachments/assets/cdfbdbb6-5200-4195-aaf0-b5d56c98c700)

It looks like the system can't find any FreeBSD specific libraries. I noticed in the readme that this library supports any platforms that raylib supports, so theoretically this should work. Is there a specific way to get this working?

**Comment by JunaMeinhold** [comment]
Hi, that's because the official raylib page didn't had any shared lib for that OS prebuild and i didn't had the time to compile them myself. FreeBSD is not Linux.

**Comment by JunaMeinhold** [comment]
You could compile raylib for FreeBSD and put it in the bin/runtimes/RID-arch/native folder. RID for FreeBSD is just "freebsd", and arch eg x64 x86 arm64 for example a full identifier would be freebsd-x64.

**Comment by AAM1075** [comment]
I could add a few DLLs for BSD and some other platforms, maybe a pull request can be created for this

**Comment by JunaMeinhold** [comment]
Sorry i prefer github actions workflow files for builds or official sources, it's not that i don't trust you, i have a strict policy for not accepting binaries from unknown sources.

**Comment by AAM1075** [comment]
That's totally understandable :)

**Comment by AAM1075** [comment]
@JunaMeinhold Can I put the FreeBSD dll in `Hexa.NET.Raylib/Hexa.NET.Raylib/native/freebsd-x64`?
If I did that would I have to copy one of these lines and change it for FreeBSD?
![image](https://github.com/user-attachments/assets/e3c62612-467a-48f8-9c4f-f8cb2c21b8bd)

I'm guessing that would require a recompile.
Also, if I was to repeat this for Linux ARM, what would I need to do? I see that windows has a win-x86 and win-x64 folder, so could I just make a linux-arm64 folder?

**Comment by AAM1075** [comment]
> You could compile raylib for FreeBSD and put it in the bin/runtimes/RID-arch/native folder. RID for FreeBSD is just "freebsd", and arch eg x64 x86 arm64 for example a full identifier would be freebsd-x64.

If I've installed the library via nuget, where is the bin folder?

**Comment by JunaMeinhold** [comment]
the bin folder is simply where your executable is means the project output folder, or you simply uncomment/modify those lines in the .csproj

![image](https://github.com/user-attachments/assets/2537bfb5-b1f3-4a03-8709-0862562b3769)

**Comment by JunaMeinhold** [comment]
i'll make a private runner for linux arm64 (a RPI 4)

**Comment by AAM1075** [comment]
> i'll make a private runner for linux arm64 (a RPI 4)

Cool :)

> the bin folder is simply where your executable is means the project output folder, or you simply uncomment/modify those lines in the .csproj
> 
> ![image](https://private-user-images.githubusercontent.com/46632782/370763668-2537bfb5-b1f3-4a03-8709-0862562b3769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTA2NTUsIm5iZiI6MTcyNzI5MDM1NSwicGF0aCI6Ii80NjYzMjc4Mi8zNzA3NjM2NjgtMjUzN2JmYjUtYjFmMy00YTAzLTg3MDktMDg2MjU2MmIzNzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE4NTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YTYzYWRjYjA4Y2ZlYmI5MTFkNzg5M2QyNWEzYTIzMWI0MzkyMmI1NjlkMDhiMTJiYTAwNTU0ZTRlZGJiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.maxTjTe-sFvLRuIZgYxtQHPwURddOL1hgy7fVRwNnSY)

I was able to make a fork of the repository which should allow me to add any platforms I should need, though `Hexa.NET.ImGui` only supports Linux, MacOS, and Windows.

My current issue to fix is figuring out a way to add native cimgui files for different platforms, which hopefully will be pretty trivial to do.

**Comment by JunaMeinhold** [comment]
you can put any binaries for any platform to the runtimes folder manually
you can find it for example here "C:\Users\juna\source\repos\Hexa.NET.ImGui\ExampleD3D11\bin\Debug\net8.0"
![image](https://github.com/user-attachments/assets/39830215-1fc6-42e1-99e4-da5143a855d3)
![image](https://github.com/user-attachments/assets/3d4eb2d6-29af-45e2-a442-f28da485d10d)

**Comment by JunaMeinhold** [comment]
(this doesn't work at the moment for raylib but with the next version after i figured out to compile raylib for windows arm64)

**Comment by AAM1075** [comment]
I see, so this will be way easier than I thought!

**Comment by JunaMeinhold** [comment]
Done, now you just have to wait for nuget

![image](https://github.com/user-attachments/assets/6b794dd8-059f-4a69-9f55-5c1bceebd4b3)

**Comment by JunaMeinhold** [comment]
One last word, just make sure to name the binaries correctly, for imgui it's just cimgui.extension, but for raylib it's libraylib.extension (for non windows) and for windows it's raylib.extension

**Comment by AAM1075** [comment]
For cimgui on Linux it's `cimgui.so`, right?

**Comment by JunaMeinhold** [comment]
Jup .so for Unix based, .dll for Windows, and .dylib for Apple.
