### ISSUE TITLE
macOS x64 binary is compiled for arm64

### ISSUE THREAD

**Issue by D-a-n-i-l-o** [HexaEngine/Hexa.NET.Raylib#2]
runtimes/osx-x64/libraylib.dylib is an arm64 binary, not x64.

```
---> System.DllNotFoundException: Unable to load shared library '../bin/Debug/net9.0/runtimes/osx-x64/native/libraylib.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(../bin/Debug/net9.0/runtimes/osx-x64/native/libraylib.dylib, 0x0001): tried: '../bin/Debug/net9.0/runtimes/osx-x64/native/libraylib.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
```

**Comment by JunaMeinhold** [comment]
Thanks for pointing that out, it was a misconfiguration in the workflows file i corrected it
![image](https://github.com/user-attachments/assets/8fc5dd0f-4ba9-4352-bcbe-0a62dc7f8c69)

Will upload a patch to nuget soon

**Comment by JunaMeinhold** [comment]
Uploaded on nuget, the new package will be available any minute.
![image](https://github.com/user-attachments/assets/df8e0241-f431-4382-b62c-54ae3db8b1fb)

**Comment by D-a-n-i-l-o** [comment]
Perfect, thank you very much! 👍
